name: Update Alerts (Full)

on:
  workflow_dispatch:        # allows manual runs
  push:                     # run automatically when these files change
    paths:
      - ".github/workflows/update-alerts.yml"
      - "requirements.txt"
      - "country_alerts.py"
      - "**/*.py"

permissions:
  contents: read

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY:      ${{ secrets.GEMINI_API_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run alerts script (FULL VERSION)
        shell: bash
        run: |
          set -e
          echo "Running full ByteSizeAlerts workflow..."
          python country_alerts.py
          echo "✅ Alerts script completed successfully."

      - name: Send Discord notification (optional)
        if: env.DISCORD_WEBHOOK_URL != ''
        run: |
          msg="ByteSizeAlerts: workflow finished successfully on $GITHUB_REF by $GITHUB_ACTOR ✅"
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"${msg}\"}" \
               "$DISCORD_WEBHOOK_URL" || echo "⚠️ Discord webhook failed (continuing)."