name: Update Alerts

on:
  workflow_dispatch:        # manual run button
  push:                     # also run on pushes that touch these files
    paths:
      - ".github/workflows/update-alerts.yml"
      - "alerts/**"
      - "scripts/**"

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Smoke test
        run: |
          echo "ByteSizeAlerts workflow is running ✅"
          python -V

      - name: Discord ping (optional; skips if no secret set)
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -H "Content-Type: application/json" \
                 -d "{\"content\":\"ByteSizeAlerts: workflow ran on $GITHUB_REF by $GITHUB_ACTOR ✅\"}" \
                 "$WEBHOOK"
          else
            echo "No DISCORD_WEBHOOK_URL; skipping Discord ping."
          fi